<?php
$title = $this->translate('Users');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/user', array('action'=>'add'));?>"><?php echo $this->translate('Add user'); ?></a>
</p>

<table class="table table-hover">
<tr>
    <th><?php echo $this->translate('ID'); ?></th>
    <th><?php echo $this->translate('Name'); ?></th>
    <th><?php echo $this->translate('Firstname'); ?></th>
    <th><?php echo $this->translate('Email'); ?></th>
    <th><?php echo $this->translate('Active?'); ?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->id);?></td>
	<td><?php echo $this->escapeHtml($user->lastname);?></td>
    <td><?php echo $this->escapeHtml($user->firstname);?></td>
    <td><?php echo $this->escapeHtml($user->email);?></td>
    <td><?php echo $user->firstname?"Oui":"Non";?></td>
    <td>
        <a href="<?php echo $this->url('admin/user',
            array('action'=>'edit', 'id' => $user->id));?>"><?php echo $this->translate('edit'); ?></a>
        <a href="<?php echo $this->url('admin/user',
            array('action'=>'delete', 'id' => $user->id));?>"><?php echo $this->translate('delete'); ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>