<?php if (count($this->pages) > 1): ?>
<ul class="breadcrumb">
    <?php foreach ($this->pages as $key => $page): ?>
        <li>
            <?php if ($key < count($this->pages) - 1): // Pas le dernier élément du fil d'ariane ?>
                <a href="<?php echo $page->getHref(); ?>"><?php echo $this->translate($page->getLabel()); ?></a>
                <span class="divider">/</span>
            <?php else: ?>
                <?php echo $this->translate($page->getLabel()); ?>
            <?php endif; ?>
        </li>
        <?php endforeach; ?>
</ul>
<?php endif; ?>