<?php
$title = $this->translate('Add costume');
$this->headTitle($title);
$this->headLink()->offsetSetStylesheet(100, $this->basePath() . '/css/bootstrap-select.min.css');
$this->headscript()->offsetSetFile(100, $this->basePath() . '/js/bootstrap-select.js');
$this->headLink()->offsetSetStylesheet(101, $this->basePath() . '/css/bootstrap-combobox.css');
$this->headscript()->offsetSetFile(101, $this->basePath() . '/js/bootstrap-combobox.js');
$this->headscript()->offsetSetFile(110, $this->basePath() . '/js/costume/form.js');
?>
<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('id', 'costume-form');
?>
<br/>
<?php echo $this->form()->openTag($form); ?>

	<div class="form-horizontal">
		<?php $element = $form->get('code'); ?>
		<div class="control-group required<?php if (count($element->getMessages())) echo " error"; ?>">
			<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
			<div class="controls">
				<?php echo $this->formElement($element->setAttributes(array('style' => 'width:100px;'))); ?>
				<?php if (count($element->getMessages())):?>
				<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
				<?php endif; ?>
			</div>
		</div>
	
		<?php $element = $form->get('label'); ?>
		<div class="control-group required<?php if (count($element->getMessages())) echo " error"; ?>">
			<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
			<div class="controls">
				<?php echo $this->formElement($element->setAttributes(array('class' => 'input-block-level'))); ?>
				<?php if (count($element->getMessages())):?>
				<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
				<?php endif; ?>
			</div>
		</div>
	</div>

	<div class="row-fluid">
	
		<div class="span6">
		
			<div class="form-horizontal">
				<?php $element = $form->get('quantity'); ?>
				<div class="control-group required<?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls fuelux">
						<?php echo $this->formUxSpinner($element); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
			</div>
				
			<?php $element = $form->get('descr'); ?>
			<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
				<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
				<div class="controls">
					<?php echo $this->formElement($element->setAttributes(array('class' => 'input-block-level', 'rows' => 4))); ?>
					<?php if (count($element->getMessages())):?>
					<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
					<?php endif; ?>
				</div>
			</div>

			<div class="form-horizontal">
				<?php $element = $form->get('size'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php echo $this->formElement($element->setAttributes(array('class' => 'combobox input-block-level', 'data-combo-class' => 'input-block-level', 'data-placeholder' => $this->translate($element->getAttribute('placeholder')?:'')))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
				
				<?php $element = $form->get('gender'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php $element->setLabelAttributes(array('class'=> 'radio col2')); ?>
						<?php echo $this->formElement($element); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
					  			
				<?php $element = $form->get('type_id'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php echo $this->formElement($element->setAttributes(array('class' => 'combobox input-block-level', 'data-combo-class' => 'input-block-level', 'data-placeholder' => $this->translate($element->getAttribute('placeholder')?:'')))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
					  			
				<?php $element = $form->get('parts_selector'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<div style="position:relative;">
							<div style="position:absolute;left:0;right:35px;">
							<?php echo $this->formElement($element->setAttributes(array('class' => 'combobox input-block-level', 'data-combo-class' => 'input-block-level', 'data-dropmenu-class' => 'dropup-menu', 'data-placeholder' => $this->translate($element->getAttribute('placeholder')?:'')))); ?>
							</div>
							<button id="part-add" type="button" class="btn" style="position:absolute;right:0;width:30px;">+</button>
						</div>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<div class="controls">
						<div id="parts-list" style="display:none;">
						</div>
					</div>
					<div class="parts-list-item" id="parts-list-item-template">
						<span class="part-label"></span>
						<input type="hidden" name="parts[]" value="" disabled="disabled"/>
						<a href="#" class="btn-remove-part btn btn-mini"><i class="icon-remove"></i></a>
					</div>
				</div>
				
				<?php $element = $form->get('primary_material_id'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php echo $this->formElement($element->setAttributes(array('class' => 'combobox input-block-level', 'data-combo-class' => 'input-block-level', 'data-placeholder' => $this->translate($element->getAttribute('placeholder')?:'')))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
					  			
				<?php $element = $form->get('secondary_material_id'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php echo $this->formElement($element->setAttributes(array('class' => 'combobox input-block-level', 'data-combo-class' => 'input-block-level', 'data-placeholder' => $this->translate($element->getAttribute('placeholder')?:'')))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
					  			
				<?php $element = $form->get('primary_color_id'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php echo $this->formColorSelect($element->setAttributes(array('class' => 'selectpicker input-block-level', 'data-width' => '100%', 'data-live-search'=> 'true', 'title' => $this->translate($element->getAttribute('placeholder')?:'')))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
					  			
				<?php $element = $form->get('secondary_color_id'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php echo $this->formColorSelect($element->setAttributes(array('class' => 'selectpicker input-block-level', 'data-width' => '100%', 'data-live-search'=> 'true', 'title' => $this->translate($element->getAttribute('placeholder')?:'')))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
				
				<?php $element = $form->get('state'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php echo $this->formElement($element->setAttributes(array('class' => 'combobox input-block-level', 'data-combo-class' => 'input-block-level', 'data-placeholder' => $this->translate($element->getAttribute('placeholder')?:'')))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
					  			
				<?php $element = $form->get('origin'); ?>
				<div class="control-group <?php if (count($element->getMessages())) echo " error"; ?>">
					<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
					<div class="controls">
						<?php echo $this->formColorSelect($element->setAttributes(array('class' => 'selectpicker input-block-level', 'data-width' => '100%', 'title' => ''))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
				
				<?php $element = $form->get('origin_details'); ?>
				<div class="control-group required<?php if (count($element->getMessages())) echo " error"; ?>">
					<div class="controls">
						<?php echo $this->formElement($element->setAttributes(array('class' => 'input-block-level'))); ?>
						<?php if (count($element->getMessages())):?>
						<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
						<?php endif; ?>
					</div>
				</div>
								  			
  			</div>
  		</div>
		
		
  		<div class="span6">
	  		
	  		Photo<br/>
	  		
	  		Tags<br/>
	  		
	  		Historique<br/>
	  		
  		</div>
	
	</div>

	<div class="control-group">
	    <div class="controls">
			<?php if ($this->cancel_url): ?>
				<a href="<?php echo $this->cancel_url; ?>" class="btn"><?php echo $this->translate('Cancel'); ?></a>
			<?php endif; ?>
			<?php echo $this->formElement($form->get('submit')->setAttributes(array('class' => 'btn btn-primary'))); ?>
		</div>
	</div>

<?php echo $this->form()->closeTag(); ?>
