<?php
$title = $this->translate('Delete costume');
$this->headTitle($title);
$costume = $this->costume;
?>
<h1><?php echo $this->translateReplace("Delete costume '%label%'", array('label' => $this->escapeHtml($costume->getLabel()))); ?></h1>

<p>
<?php echo $this->translateReplace("Are you sure that you want to delete costume <b>%label%</b> (%code%)?", array('label' => $this->escapeHtml($costume->getLabel()), 'code' => $this->escapeHtml($costume->getCode()))); ?>
</p>

<?php
$url = $this->url('costume', array(
    'action' => 'delete',
    'id'     => (int) $costume->getId(),
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $costume->getId(); ?>" />
    <button type="submit" class="btn" name="del" value="no"><?php echo $this->translate('No'); ?></button>
    <button type="submit" class="btn btn-primary" name="del" value="yes"><?php echo $this->translate('Yes'); ?></button>
</div>
</form>
