<?php
$this->headscript()->offsetSetFile(100, $this->basePath() . '/js/typeahead.bundle.min.js');
$this->headscript()->offsetSetFile(101, $this->basePath() . '/js/handlebars-v1.3.0.js');

$title = $this->translate('Costumes');
$this->headTitle($title);

$form = $this->form;
$form->prepare();
?>
<form id="costume-search-form" class="form-search">

	<?php $element = $form->get('q'); ?>
	<div id="small-search-form" class="pull-right input-append">
		<?php echo $this->formElement($element->setAttributes(array('class' => 'input-medium search-query'))); ?>
		<span id="small-search-form-completion-loader"></span>
		<button type="submit" id="small-search-button" class="btn" title="<?php echo $this->translate('Search'); ?>"><i class="icon-search"></i></button>
		<?php if ($this->has_search): ?>
		<a id="small-cancel-search-button" href="<?php echo $this->url(); ?>" class="btn btn-danger" title="<?php echo $this->translate('Cancel search'); ?>"><i class="icon-remove"></i></a>
		<?php endif; ?>
		<button type="button" id="more-search-form" class="btn" title="<?php echo $this->translate('Show more search options...'); ?>"><i class="caret"></i></button>
	</div>
	
	<div class="p action-bar action-bar-container">
		<?php if ($this->acl()->isAllowed("add_costume")): ?>
		<div class="action-bar-item">
		<a href="<?php echo $this->url('costume', array('action'=>'add'));?>"><i class="icon-plus-sign icon-linkcolor"></i> <?php echo $this->translate('Add costume'); ?></a>
		</div>
		<?php endif; ?>
	</div>
	
	<div id="full-search-form" style="display:none;">
	    <label class="control-label" for="inputEmail">Email</label>
	    <div class="controls">
	      <input type="text" id="inputEmail" placeholder="Email">
	    </div>
	</div>
</form>

<?php if (count($this->costumes)): ?>
<table class="table table-hover">
<thead>
<tr>
    <th>
    	<?php echo $this->partial("table-sorter", array('field' => 'code', 'sort' => $this->sort, 'direction' => $this->direction, 'route_parameters' => array(), 'get_parameters' => $this->get_parameters)); ?>
    	<?php echo $this->translate('Code'); ?>
    </th>
    <th>
    	<?php echo $this->partial("table-sorter", array('field' => 'label', 'sort' => $this->sort, 'direction' => $this->direction, 'route_parameters' => array(), 'get_parameters' => $this->get_parameters)); ?>
    	<?php echo $this->translate('Name'); ?>
    </th>
    <th class="text-center">
    	<?php echo $this->partial("table-sorter", array('field' => 'type', 'sort' => $this->sort, 'direction' => $this->direction, 'route_parameters' => array(), 'get_parameters' => $this->get_parameters)); ?>
    	<?php echo $this->translate('Type'); ?>
    </th>
    <th class="text-center">
    	<?php echo $this->partial("table-sorter", array('field' => 'gender', 'sort' => $this->sort, 'direction' => $this->direction, 'route_parameters' => array(), 'get_parameters' => $this->get_parameters)); ?>
    	<?php echo $this->translate('Gender'); ?>
    </th>
    <th class="text-center">
    	<?php echo $this->partial("table-sorter", array('field' => 'size', 'sort' => $this->sort, 'direction' => $this->direction, 'route_parameters' => array(), 'get_parameters' => $this->get_parameters)); ?>
    	<?php echo $this->translate('Size'); ?>
    </th>
    <th class="text-center"><?php echo $this->translate('Colors'); ?></th>
    <th class="text-center"><?php echo $this->translate('Materials'); ?></th>
    <th class="text-center">
    	<?php echo $this->partial("table-sorter", array('field' => 'quantity', 'sort' => $this->sort, 'direction' => $this->direction, 'route_parameters' => array(), 'get_parameters' => $this->get_parameters)); ?>
    	<?php echo $this->translate('Quantity'); ?>
    </th>
    <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->costumes as $costume) : ?>
<tr>
	<td>
		<?php if ($this->acl()->isAllowed("show_costume")): ?>
		<a href="<?php echo $this->url('costume', array('action'=>'show', 'id' => $costume->getId()));?>"><?php echo $this->escapeHtml($costume->getCode());?></a>
		<?php else: ?>
		<?php echo $this->escapeHtml($costume->getCode());?>
		<?php endif;?>
		</td>
    <td>
		<?php if ($this->acl()->isAllowed("show_costume")): ?>
		<a href="<?php echo $this->url('costume', array('action'=>'show', 'id' => $costume->getId()));?>"><?php echo $this->escapeHtml($costume->getLabel());?></a>
		<?php else: ?>
    	<?php echo $this->escapeHtml($costume->getLabel());?>
		<?php endif;?>
    </td>
    <td class="text-center">
    	<?php $type = $costume->getType(); ?>
		<?php if ($type): ?>
		<?php echo $this->escapeHtml($type->getName()); ?>
		<?php endif; ?>
	</td>
    <td class="text-center">
    	<?php echo $this->escapeHtml($costume->getGender());?>
    </td>
    <td class="text-center">
    	<?php echo $this->escapeHtml($costume->getSize());?>
    </td>
    <td class="text-center">
		<?php $primaryColor = $costume->getPrimaryColor();?>
		<?php if ($primaryColor): ?>
			<div class="costume-color-preview no-margin" style="background-color:#<?php echo $primaryColor->getColorCode(); ?>;" title="<?php echo $this->escapeHtmlAttr($this->translate($primaryColor->getName())); ?>"></div>
		<?php else: ?>
			<div class="costume-color-preview no-margin no-color" title="<?php echo $this->escapeHtmlAttr($this->translate('No color')); ?>"></div>
		<?php endif;?>
		<?php $secondaryColor = $costume->getSecondaryColor();?>
		<?php if ($secondaryColor): ?> 
			<div class="costume-color-preview no-margin" style="background-color:#<?php echo $secondaryColor->getColorCode(); ?>;" title="<?php echo $this->escapeHtmlAttr($this->translate($secondaryColor->getName())); ?>"></div>
		<?php else: ?>
			<div class="costume-color-preview no-margin no-color" title="<?php echo $this->escapeHtmlAttr($this->translate('No color')); ?>"></div>
		<?php endif;?>
	</td>
    <td class="text-center">
    	<?php $materials = array();
		$primaryMaterial = $costume->getPrimaryMaterial();
		if ($primaryMaterial) {
			$materials[] = $this->escapeHtml($primaryMaterial->getName());
		}
		$secondaryMaterial = $costume->getSecondaryMaterial();
		if ($secondaryMaterial) {
			if (!$primaryMaterial) {
				$materials[] = $this->translate('N/A');
			}
			$materials[] = $this->escapeHtml($secondaryMaterial->getName());
		} ?>
		<small><?php echo join(' / ', $materials); ?></small>
	</td>
	<td class="text-center">
    	<?php echo $this->escapeHtml($costume->getQuantity());?>
    </td>
    <td class="text-right action-bar action-bar-container">
		<?php if ($this->acl()->isAllowed("edit_costume")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('costume',
            array('action'=>'edit', 'id' => $costume->getId()));?>" title="<?php echo $this->translate('edit'); ?>"><i class="icon-edit icon-linkcolor"></i></a>
        </div> 
		<?php endif;?>
    	<?php if ($this->acl()->isAllowed("delete_costume")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('costume',
            array('action'=>'delete', 'id' => $costume->getId()));?>" title="<?php echo $this->translate('delete'); ?>"><i class="icon-trash icon-linkcolor"></i></a>
        </div> 
    	<?php endif;?>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php if ($this->costumes instanceof Zend\Paginator\Paginator): ?>
<div class="pagination-placeholder">
<?php echo $this->paginationControl($this->costumes, 'Sliding', 'paginator/sliding', 
		array('route' => 'costume', 'route_parameters' => array(), 'get_parameters' => $this->get_parameters, 'context' => 'costume-list', 'affix' => true)); ?>
</div>
<?php endif; ?>
<?php else: ?>
<div class="well" style="margin-top:20px;">
<?php echo $this->translate('No costumes.'); ?>
</div>
<?php endif; ?>

<script type="text/javascript">
$(function() {
	$('#more-search-form').click(function(e) {
		e.preventDefault();

		var $fullForm = $('#full-search-form');
		var $moreSearchButton = $('#more-search-form');
		
		if ($fullForm.is(':visible')) {
			$fullForm.hide();
			$moreSearchButton.removeClass('active');
		} else {
			$fullForm.show();
			$moreSearchButton.addClass('active');
		}
		$moreSearchButton.blur();
	});

	var costumeCompletion = new Bloodhound({
		remote: {
			url: '<?php echo $this->url('costume', array('action'=>'searchcmpl')); ?>?q=%QUERY&max=8',
			filter: function(parsedResponse) {
				return parsedResponse.results;
			},
			ajax: {
				beforeSend: function() {
					$('#small-search-form-completion-loader').show();
				},
				complete: function() {
					$('#small-search-form-completion-loader').hide();
				}
			}
		},
		limit: 8,
		datumTokenizer: function(d) { 
		    return Bloodhound.tokenizers.whitespace(d.val); 
		},
		queryTokenizer: Bloodhound.tokenizers.whitespace
	});

	costumeCompletion.initialize();

	$('#input-q').typeahead({
			minLength: 2
		}, {
			name: 'costume-completion',
			source: costumeCompletion.ttAdapter(),
		 	displayKey: 'label',
			templates: {
				suggestion: Handlebars.compile([
				    '<div class="costume-suggestion">',
					'<div class="costume-code">{{code}}</div>',
					'<div class="costume-label">{{label}}</div>',
					'</div>'
					].join(''))
		}
	}).on('typeahead:selected', function(typeahead, costume, name) {
		window.location.href = '<?php echo $this->url('costume', array('action'=>'show'));?>/'+costume.id;
	});
	$('#small-search-form-completion-loader').appendTo($('#small-search-form > .twitter-typeahead'));
});
</script>