<?php
$title = $this->translate('Costumes');
$this->headTitle($title);
?>
<div class="p action-bar action-bar-container">
	<?php if ($this->acl()->isAllowed("add_costume")): ?>
	<div class="action-bar-item">
	<a href="<?php echo $this->url('costume', array('action'=>'add'));?>"><i class="icon-plus-sign icon-linkcolor"></i> <?php echo $this->translate('Add costume'); ?></a>
	</div>
	<?php endif; ?>
</div>

<?php if (count($this->costumes)): ?>
<table class="table table-hover">
<thead>
<tr>
    <th><?php echo $this->translate('Code'); ?></th>
    <th><?php echo $this->translate('Name'); ?></th>
    <th class="text-center"><?php echo $this->translate('Type'); ?></th>
    <th class="text-center"><?php echo $this->translate('Gender'); ?></th>
    <th class="text-center"><?php echo $this->translate('Size'); ?></th>
    <th class="text-center"><?php echo $this->translate('Colors'); ?></th>
    <th class="text-center"><?php echo $this->translate('Materials'); ?></th>
    <th class="text-center"><?php echo $this->translate('Quantity'); ?></th>
    <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->costumes as $costume) : ?>
<tr>
	<td>
		<?php if ($this->acl()->isAllowed("show_costume")): ?>
		<a href="<?php echo $this->url('costume', array('action'=>'show', 'id' => $costume->getId()));?>"><?php echo $this->escapeHtml($costume->getCode());?></a>
		<?php else: ?>
		<?php echo $this->escapeHtml($costume->getCode());?>
		<?php endif;?>
		</td>
    <td>
		<?php if ($this->acl()->isAllowed("show_costume")): ?>
		<a href="<?php echo $this->url('costume', array('action'=>'show', 'id' => $costume->getId()));?>"><?php echo $this->escapeHtml($costume->getLabel());?></a>
		<?php else: ?>
    	<?php echo $this->escapeHtml($costume->getLabel());?>
		<?php endif;?>
    </td>
    <td class="text-center">
    	<?php $type = $costume->getType(); ?>
		<?php if ($type): ?>
		<?php echo $this->escapeHtml($type->getName()); ?>
		<?php endif; ?>
	</td>
    <td class="text-center">
    	<?php echo $this->escapeHtml($costume->getGender());?>
    </td>
    <td class="text-center">
    	<?php echo $this->escapeHtml($costume->getSize());?>
    </td>
    <td class="text-center">
		<?php $primaryColor = $costume->getPrimaryColor();?>
		<?php if ($primaryColor): ?>
			<div class="costume-color-preview no-margin" style="background-color:#<?php echo $primaryColor->getColorCode(); ?>;" title="<?php echo $this->escapeHtmlAttr($this->translate($primaryColor->getName())); ?>"></div>
		<?php else: ?>
			<div class="costume-color-preview no-margin no-color" title="<?php echo $this->escapeHtmlAttr($this->translate('No color')); ?>"></div>
		<?php endif;?>
		<?php $secondaryColor = $costume->getSecondaryColor();?>
		<?php if ($secondaryColor): ?> 
			<div class="costume-color-preview no-margin" style="background-color:#<?php echo $secondaryColor->getColorCode(); ?>;" title="<?php echo $this->escapeHtmlAttr($this->translate($secondaryColor->getName())); ?>"></div>
		<?php else: ?>
			<div class="costume-color-preview no-margin no-color" title="<?php echo $this->escapeHtmlAttr($this->translate('No color')); ?>"></div>
		<?php endif;?>
	</td>
    <td class="text-center">
    	<?php $materials = array();
		$primaryMaterial = $costume->getPrimaryMaterial();
		if ($primaryMaterial) {
			$materials[] = $this->escapeHtml($primaryMaterial->getName());
		}
		$secondaryMaterial = $costume->getSecondaryMaterial();
		if ($secondaryMaterial) {
			if (!$primaryMaterial) {
				$materials[] = $this->translate('N/A');
			}
			$materials[] = $this->escapeHtml($secondaryMaterial->getName());
		} ?>
		<small><?php echo join(' / ', $materials); ?></small>
	</td>
	<td class="text-center">
    	<?php echo $this->escapeHtml($costume->getQuantity());?>
    </td>
    <td class="text-right action-bar action-bar-container">
		<?php if ($this->acl()->isAllowed("edit_costume")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('costume',
            array('action'=>'edit', 'id' => $costume->getId()));?>" title="<?php echo $this->translate('edit'); ?>"><i class="icon-edit icon-linkcolor"></i></a>
        </div> 
		<?php endif;?>
    	<?php if ($this->acl()->isAllowed("delete_costume")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('costume',
            array('action'=>'delete', 'id' => $costume->getId()));?>" title="<?php echo $this->translate('delete'); ?>"><i class="icon-trash icon-linkcolor"></i></a>
        </div> 
    	<?php endif;?>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php if ($this->costumes instanceof Zend\Paginator\Paginator): ?>
<?php echo $this->paginationControl($this->costumes, 'Sliding', 'paginator/sliding', 
		array('route' => 'costume', 'route_parameters' => array(), 'get_parameters' => $this->get_parameters, 'context' => 'costume-list')); ?>
<?php endif; ?>
<?php else: ?>
<div class="well">
<?php echo $this->translate('No costumes.'); ?>
</div>
<?php endif; ?>