<?php
$title = $this->translate('Change costume picture');
$this->headTitle($title);
$this->headscript()->offsetSetFile(100, $this->basePath() . '/js/bootstrap-fileupload.js');
?>
<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>

<?php 
if ($this->form && $this->costume) {

$costume = $this->costume;
$form = $this->form;
$form->setAttribute('id', 'costume-picture-form');
$form->prepare(); ?>
<br />
<?php echo $this->form()->openTag($form); ?>

<div class="row-fluid">

	<div class="span4 well">
		<h4 style="margin-top: 0;"><?php echo $this->escapehtml($costume->getLabel()); ?> <em>(<?php echo $this->escapehtml($costume->getCode()); ?>)</em>
		</h4>
		<b><?php echo $this->translate('Current picture: ');?></b><br />
	
		<?php if (count($costume->getPictures())): ?>
		<?php $mainPicture = $costume->getPictures()->current(); ?>
		<?php $landscapePicture = ($mainPicture->getOrientation() == Application\Model\Picture::ORIENTATION_LANDSCAPE); ?>
		<a class="thumbnail pull-left zoom-in-cursor span12"
			href="<?php echo $mainPicture->getUrlPath(); ?>" target="_blank"
			style="margin: 0;"> <img class="media-object"
			src="<?php echo $mainPicture->getUrlPath(); ?>">
		</a>
		<?php else: ?>
		<?php $landscapePicture = true; ?>
		<div class="thumbnail pull-left no-picture text-center span12" style="margin: 0; background-color:white;">
			<img class="media-object" src="/img/costume/no-costume.png"> <small><?php echo $this->translate('No picture'); ?></small>
		</div>
		<?php endif; ?>
		
	</div>

	<div class="span8">
			<?php $element = $form->get('picture_file'); ?>
			<div class="fileupload fileupload-new control-group <?php if (count($element->getMessages())) echo " error"; ?>" data-provides="fileupload">
			<div class="fileupload-new thumbnail drop-zone" id="picture-drop-zone" style="max-width: 300px; vertical-align:middle;">
				<img class="media-object" src="/img/costume/no-costume.png"> <small><?php echo $this->translate('No picture'); ?></small>
			</div>
			<div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 300px; max-height: 300px; line-height: 20px;"></div>
			<?php if (count($element->getMessages())):?>
			<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
			<?php endif; ?>
			<div>
				<span class="btn btn-file">
					<span class="fileupload-new"><?php echo $this->translate('Select picture'); ?></span>
					<span class="fileupload-exists"><?php echo $this->translate('Select another picture'); ?></span>
					<?php echo $this->formElement($element); ?>
				</span>
				<a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><?php echo $this->translate('No picture'); ?></a>
			</div>
		</div>
		
		<div class="form-buttons">
			<div class="controls">
				<?php if ($this->cancel_url): ?>
					<a href="<?php echo $this->cancel_url; ?>" class="btn"><?php echo $this->translate('Cancel'); ?></a>
				<?php endif; ?>
				<?php echo $this->formElement($form->get('submit')->setAttributes(array('class' => 'btn btn-primary'))); ?>
			</div>
		</div>

	</div>

</div>
<?php 
echo $this->form()->closeTag(); 
} // $this->form 
?>

<?php if (count($costume->getPictures())): ?>
<div id="delete-picture-confirm" class="modal hide fade" tabindex="-1">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3 id="myModalLabel"><?php echo $this->translate("Delete the costume's picture?"); ?></h3>
  </div>
  <div class="modal-body">
  <h1 class="icon-warning-sign text-error pull-left"></h1>
    <p><?php echo $this->translate("You have not selected image. This will permanently delete the image already attached to the costume."); ?></p>
    <p><?php echo $this->translate("Do you really want to delete this picture?"); ?></p>
    </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal"><?php echo $this->translate('No'); ?></button>
    <button class="btn btn-primary" id="delete-picture-confirm-yes"><?php echo $this->translate('Yes'); ?></button>
  </div>
</div>

<script type="text/javascript">
$(function() {
	$('#costume-picture-form').submit(function(e) {
		if (!$('#input-picture').val().length) {
			if ($(this).data('delete_confirmed')) {
			} else {
				$('#delete-picture-confirm').modal('show');
				return false;
			}
		}
	});

	$('#delete-picture-confirm-yes').click(function (e) {
		$('#delete-picture-confirm').modal('hide');
		$('#costume-picture-form').data('delete_confirmed', true);
		$('#picture-save-button').trigger('click');
});
});
</script>
<?php endif; ?>
