<?php
/* @var $costume \Costume\Model\Costume */
$costume = $this->costume;
$title = $this->translateReplace('Costume: %label%', array('label' => $costume->getLabel()));
$this->headTitle($title);
?>
<div class="page-qrcode-container hidden-phone hidden-tablet">
	<div class="page-qrcode-holder">
		<div class="thumbnail text-center pull-right page-qrcode">
			<img src="https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl=<?php echo urlencode($this->serverUrl(true)); ?>"/>
			<small><?php echo $costume->getCode(); ?></small>
		</div>
	</div>
</div>
<div class="pull-right hidden-phone hidden-tablet text-right muted" style="margin-right:20px;">
<small>
<?php echo $this->translate('Record created '); ?><?php echo $costume->getCreationDate($this->translate('full_text_date_time')) ?><br/>
<?php echo $this->translate('Record modified '); ?><?php echo $costume->getLastModificationDate($this->translate('full_text_date_time')) ?>
</small>
</div>
<h2><?php echo $this->escapeHtml($costume->getLabel()); ?></h2>
<div class="p action-bar action-bar-container" style="margin-bottom:20px;">
		<?php if ($this->acl()->isAllowed("edit_costume")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('costume',
            array('action'=>'edit', 'id' => $costume->getId()));?>"><i class="icon-edit icon-linkcolor"></i> <?php echo $this->translate('edit'); ?></a>
        </div> 
		<div class="action-bar-item">
        <a href="<?php echo $this->url('costume',
            array('action'=>'picture', 'id' => $costume->getId()));?>"><i class="icon-picture icon-linkcolor"></i> <?php echo $this->translate('change picture'); ?></a>
        </div> 
        <?php endif;?>
    	<?php if ($this->acl()->isAllowed("delete_costume")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('costume',
            array('action'=>'delete', 'id' => $costume->getId()));?>"><i class="icon-trash icon-linkcolor"></i> <?php echo $this->translate('delete'); ?></a>
        </div> 
    	<?php endif;?>
</div>
<div class="row-fluid">
	<?php if (count($costume->getPictures())): ?>
	<?php $mainPicture = $costume->getPictures()->current(); ?>
	<?php $landscapePicture = ($mainPicture->getOrientation() == Application\Model\Picture::ORIENTATION_LANDSCAPE); ?>
	<a class="thumbnail pull-left zoom-in-cursor span<?php echo $landscapePicture?4:3; ?>" href="<?php echo $mainPicture->getUrlPath(); ?>" target="_blank">
		<img class="media-object" src="<?php echo $mainPicture->getUrlPath(); ?>">
	</a>
	<?php else: ?>
	<?php $landscapePicture = true; ?>
	<div class="thumbnail pull-left span4 no-picture text-center">
		<img class="media-object" src="/img/costume/no-costume.png">
		<small><?php echo $this->translate('No picture'); ?></small>
	</div>
	<?php endif; ?>
	
	<div class="span<?php echo $landscapePicture?4:5; ?>">
		<?php echo $this->text2html($costume->getDescr()); ?>
		<?php $tags = $costume->getTags(); ?>
		<?php if (count($tags)): ?>
		<ul class="unstyled" style="margin-top:10px;">
		<?php foreach ($tags as $tag): ?>
		<li><i class="icon-tag"></i> <?php echo $this->escapeHtml($tag->getName()); ?></li>
		<?php endforeach; ?>
		</ul>
		<?php endif; ?>
		<div class="p">
			<b><?php echo $this->translate('Type:'); ?></b>
				<?php $type = $costume->getType(); ?>
				<?php if ($type): ?>
					<?php echo $this->escapeHtml($this->translate($type->getName())); ?>
				<?php else: ?>
					&nbsp;
				<?php endif;?>
			<?php $parts = $costume->getParts();?>
			<?php if (count($parts)): ?>
			<br/>
			<b><?php echo $this->translate('Parts:'); ?></b>
			<ul style="margin-bottom:0px;">
			<?php foreach ($parts as $part): ?>
			<li><?php echo $this->escapeHtml($part->getName()); ?></li>
			<?php endforeach; ?>
			</ul>
			<?php endif; // count($parts) ?>
		</div>
		<?php $history = $costume->getHistory(); ?>
		<?php if (!empty($history)): ?>
		<div class="p">
			<b><?php echo $this->translate('History:'); ?></b><br/>
			<?php echo $this->text2html($history); ?>
		</div>
		<?php endif; ?>
	</div>
	
	<div class="span4">
		<div class="row-fluid">
			<div class="span6">
				<dl class="no-margin">
					<dt><?php echo $this->translate('Gender:'); ?></dt>
					<dd><?php echo $costume->getGender()?$this->escapeHtml($this->translate($costume->getGender())):''; ?>&nbsp;</dd>
					<dt><?php echo $this->translate('Size:'); ?></dt>
					<dd><?php echo $this->escapeHtml($costume->getSize()); ?>&nbsp;</dd>
					<dt><?php echo $this->translate('State:'); ?></dt>
					<dd><?php echo $this->escapeHtml($costume->getState()); ?>&nbsp;</dd>
					<dt><?php echo $this->translate('Quantity:'); ?></dt>
					<dd><?php echo $this->escapeHtml($costume->getQuantity()); ?>&nbsp;</dd>
				</dl>		
			</div>
			<div class="span6">
				<dl class="no-margin">
					<dt><?php echo $this->translate('Primary color:'); ?></dt>
					<dd>
						<?php $primaryColor = $costume->getPrimaryColor(); ?>
						<?php if ($primaryColor): ?>
							<div class="costume-color-preview" style="background-color:#<?php echo $primaryColor->getColorCode(); ?>;"></div>
							<?php echo $this->escapeHtml($this->translate($primaryColor->getName())); ?>
						<?php else: ?>
							&nbsp;
						<?php endif;?>
					</dd>
					<dt><?php echo $this->translate('Secondary color:'); ?></dt>
					<dd>
						<?php $secondaryColor = $costume->getSecondaryColor(); ?>
						<?php if ($secondaryColor): ?>
							<div class="costume-color-preview" style="background-color:#<?php echo $secondaryColor->getColorCode(); ?>;"></div>
							<?php echo $this->escapeHtml($this->translate($secondaryColor->getName())); ?>
						<?php else: ?>
							&nbsp;
						<?php endif;?>
					</dd>
					<dt><?php echo $this->translate('Primary material:'); ?></dt>
					<dd>
						<?php $primaryMaterial = $costume->getPrimaryMaterial(); ?>
						<?php if ($primaryMaterial): ?>
							<?php echo $this->escapeHtml($this->translate($primaryMaterial->getName())); ?>
						<?php else: ?>
							&nbsp;
						<?php endif;?>
					</dd>
					<dt><?php echo $this->translate('Secondary material:'); ?></dt>
					<dd>
						<?php $secondaryMaterial = $costume->getSecondaryMaterial(); ?>
						<?php if ($secondaryMaterial): ?>
							<?php echo $this->escapeHtml($this->translate($secondaryMaterial->getName())); ?>
						<?php else: ?>
							&nbsp;
						<?php endif;?>
					</dd>
				</dl>		
			</div>
			<dl class="no-margin">
				<dt><?php echo $this->translate('Origin:'); ?></dt>
				<dd>
					<?php $origin = $costume->getOrigin(); ?>
					<?php if ($origin): ?>
						<?php echo $this->escapeHtml($this->translate($origin)); ?>
						<?php $originDetails = $costume->getOriginDetails(); ?> 
						<?php if (!empty($originDetails)): ?>
							<br/><?php echo $this->escapeHtml($originDetails); ?>
						<?php endif; ?>
					<?php else: ?>
						&nbsp;
					<?php endif; ?>
				</dd>
			</dl>		
		</div>
	</div>
</div>
<?php if ($this->return_url): ?>
<p style="margin-top:20px;">
<a href="<?php echo $this->return_url; ?>" class="btn btn-primary"><?php echo $this->translate('Back'); ?></a>
</p>
<?php endif; ?>

