<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Acl\Module'                                   => __DIR__ . '/Module.php',
    'AclTest\Helper\AclHelperTest'                 => __DIR__ . '/test/AclTest/Helper/AclHelperTest.php',
    'AclTest\Bootstrap'                            => __DIR__ . '/test/Bootstrap.php',
    'Acl\Helper\AclHelper'                         => __DIR__ . '/src/Acl/Helper/AclHelper.php',
    'Acl\Form\Role'                                => __DIR__ . '/src/Acl/Form/Role.php',
    'Acl\Form\RoleFilter'                          => __DIR__ . '/src/Acl/Form/RoleFilter.php',
    'Acl\View\Helper\Acl'                          => __DIR__ . '/src/Acl/View/Helper/Acl.php',
    'Acl\Controller\AdminRightController'          => __DIR__ . '/src/Acl/Controller/AdminRightController.php',
    'Acl\Controller\AdminRoleController'           => __DIR__ . '/src/Acl/Controller/AdminRoleController.php',
    'Acl\Controller\Plugin\Acl'                    => __DIR__ . '/src/Acl/Controller/Plugin/Acl.php',
    'Acl\Controller\UnauthorizedController'        => __DIR__ . '/src/Acl/Controller/UnauthorizedController.php',
    'Acl\Controller\AclControllerInterface'        => __DIR__ . '/src/Acl/Controller/AclControllerInterface.php',
    'Acl\Controller\AclConsoleControllerInterface' => __DIR__ . '/src/Acl/Controller/AclConsoleControllerInterface.php',
    'Acl\Model\RightsManager'                      => __DIR__ . '/src/Acl/Model/RightsManager.php',
    'Acl\Model\Role'                               => __DIR__ . '/src/Acl/Model/Role.php',
    'Acl\Model\RolesManager'                       => __DIR__ . '/src/Acl/Model/RolesManager.php',
    'Acl\Model\AclManager'                         => __DIR__ . '/src/Acl/Model/AclManager.php',
    'Acl\Model\RoleTable'                          => __DIR__ . '/src/Acl/Model/RoleTable.php',
);
