<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'partial/rights-list'   => __DIR__ . '/view/partial/rights-list.phtml',
    'acl/admin-role/show'   => __DIR__ . '/view/acl/admin-role/show.phtml',
    'acl/admin-role/delete' => __DIR__ . '/view/acl/admin-role/delete.phtml',
    'acl/admin-role/edit'   => __DIR__ . '/view/acl/admin-role/edit.phtml',
    'acl/admin-role/add'    => __DIR__ . '/view/acl/admin-role/add.phtml',
    'acl/admin-role/index'  => __DIR__ . '/view/acl/admin-role/index.phtml',
    'acl/admin-right/index' => __DIR__ . '/view/acl/admin-right/index.phtml',
);
