<div id="forgotpassword-form-container">
<?php
$form = $this->forgotPasswordForm;
?>
	<p>
	<?php echo $this->translate("<b>You have forgot your password?</b><br/>Don't worry, we will help you recover your account, provided that you remember the email address, which must be valid."); ?> 
	</p>

	<?php echo $this->form()->openTag($form) ?>
	
	<div class="control-group<?php if (count($form->get('email')->getMessages())) echo " error"; ?>">
		<div class="input-prepend input-append">
		<span class="add-on"><b>@</b></span>
		<?php echo $this->formInput($form->get('email')) ?>
		<?php echo $this->formButton($form->get('submit')->setAttributes(array('class' => 'btn btn-primary'))); ?>
		</div>
		<?php if (count($form->get('email')->getMessages())):?>
		<span class="help-block"><?php echo $this->formElementErrors($form->get('email')); ?></span>
		<?php endif; ?>
	</div>
	
	<?php echo $this->form()->closeTag() ?>
</div>