<?php if ($this->error_message): ?>
<div class="alert alert-block alert-error" style="width:500px;margin:0 auto;">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4><?php echo $this->translate('Login failed'); ?></h4>
  <?php echo $this->translate($this->error_message); ?>
</div>
<?php endif; ?>
<div id="login-form-container">
<?php
$form = $this->loginForm;
?>
<?php echo $this->form()->openTag($form) ?>

        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <div class="input-prepend">
            <span class="add-on"><b>@</b></span>
            <?php echo $this->formInput($form->get('identity')) ?>
        </div>

        <div class="input-prepend">
            <span class="add-on"><i class="icon-lock"></i></span>
            <?php echo $this->formInput($form->get('credential')) ?>
        </div>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>
        
        <div style="text-align:center;">
            <?php echo $this->formButton($form->get('submit')->setAttributes(array('class' => 'btn btn-primary btn-block'))); ?>
        </div>
        
<?php echo $this->form()->closeTag() ?>
</div>