<?php
$title = $this->translate('Add user');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'user-form');
?>
<br/>
<?php echo $this->form()->openTag($form); ?>
	
	<?php $element = $form->get('firstname'); ?>
	<div class="control-group<?php if (count($element->getMessages())) echo " error"; ?>">
		<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
		<div class="controls">
			<?php echo $this->formElement($element) ?><span class="help-inline"><?php echo $this->translate('Recommended.'); ?></span>
			<?php if (count($element->getMessages())):?>
			<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
			<?php endif; ?>
		</div>
	</div>

	<?php $element = $form->get('lastname'); ?>
	<div class="control-group<?php if (count($element->getMessages())) echo " error"; ?>">
		<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
		<div class="controls">
			<?php echo $this->formElement($element) ?><span class="help-inline"><?php echo $this->translate('Recommended.'); ?></span>
			<?php if (count($element->getMessages())):?>
			<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
			<?php endif; ?>
		</div>
	</div>

	<?php $element = $form->get('email'); ?>
	<div class="control-group required<?php if (count($element->getMessages())) echo " error"; ?>">
		<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
		<div class="controls">
			<?php echo $this->formElement($element) ?><span class="help-inline"><?php echo $this->translate('Mandatory. Used as login credential.'); ?></span>
			<?php if (count($element->getMessages())):?>
			<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
			<?php endif; ?>
			<div class="help-block">
			<?php echo $this->translate("The user will receive an email to validate its account and set the password."); ?>
			</div>
		</div>
	</div>

	<?php $element = $form->get('roles'); ?>
	<div class="control-group<?php if (count($element->getMessages())) echo " error"; ?>">
		<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
		<div class="controls">
			<?php echo $this->formElement($element->setLabelAttributes(array('class'=> 'multicheckbox'))) ?>
			<?php if (count($element->getMessages())):?>
			<span class="help-block"><?php echo $this->formElementErrors($element); ?></span>
			<?php endif; ?>
		</div>
	</div>
	
	<?php $element = $form->get('active'); ?>
	<div class="control-group">
		<?php echo $this->formLabel($element->setLabelAttributes(array('class'=> 'control-label'))); ?>
		<div class="controls">
			<?php echo $this->formElement($element) ?>
		</div>
	</div>
	
	<div class="control-group">
	    <div class="controls">
			<?php if ($this->cancel_url): ?>
				<a href="<?php echo $this->cancel_url; ?>" class="btn"><?php echo $this->translate('Cancel'); ?></a>
			<?php endif; ?>
			<?php echo $this->formElement($form->get('submit')->setAttributes(array('class' => 'btn btn-primary'))); ?>
		</div>
	</div>

<?php echo $this->form()->closeTag(); ?>

