<?php
$title = 'Delete user';
$this->headTitle($title);
$user = $this->user;
?>
<h1><?php echo $this->translateReplace('Delete user %displayName%', array('displayName' => $this->escapeHtml($user->getDisplayName()))); ?></h1>

<?php if ($this->own_user): ?>
<div class="alert alert-error">
	<?php echo $this->translate("You can't delete your own user account."); ?>
</div>
<?php if ($this->return_url): ?>
<p>
<a href="<?php echo $this->return_url; ?>" class="btn btn-primary"><?php echo $this->translate('Back'); ?></a>
</p>
<?php endif; ?>
<?php else: ?>
<p>
<?php echo $this->translateReplace("Are you sure that you want to delete user '%displayName%' (%email%)?", array('displayName' => $this->escapeHtml($user->getDisplayName()), 'email' => $this->escapeHtml($user->getEmail()))); ?>
</p>

<?php
$url = $this->url('admin/user', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $user->getId(); ?>" />
    <button type="submit" class="btn" name="del" value="no"><?php echo $this->translate('No'); ?></button>
    <button type="submit" class="btn btn-primary" name="del" value="yes"><?php echo $this->translate('Yes'); ?></button>
</div>
</form>
<?php endif; ?>