<?php
$title = $this->translate('Users');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="p action-bar action-bar-container">
	<?php if ($this->acl()->isAllowed("admin_add_user")): ?>
	<div class="action-bar-item">
	<a href="<?php echo $this->url('admin/user', array('action'=>'add'));?>"><i class="icon-plus-sign icon-linkcolor"></i> <?php echo $this->translate('Add user'); ?></a>
	</div>
	<?php endif; ?>
</div>

<?php if (count($this->users)): ?>
<table class="table table-hover">
<thead>
<tr>
    <th><?php echo $this->translate('ID'); ?></th>
    <th><?php echo $this->translate('Name'); ?></th>
    <th><?php echo $this->translate('Firstname'); ?></th>
    <th><?php echo $this->translate('Email'); ?></th>
    <th><?php echo $this->translate('Enabled?'); ?></th>
    <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->getId());?></td>
	<td>
		<?php if ($this->acl()->isAllowed("admin_add_user")): ?>
		<a href="<?php echo $this->url('admin/user', array('action'=>'show', 'id' => $user->getId()));?>"><?php echo $this->escapeHtml($user->getLastname());?></a>
		<?php else: ?>
		<?php echo $this->escapeHtml($user->getLastname());?>
		<?php endif;?>
		</td>
    <td>
		<?php if ($this->acl()->isAllowed("admin_add_user")): ?>
    	<a href="<?php echo $this->url('admin/user', array('action'=>'show', 'id' => $user->getId()));?>"><?php echo $this->escapeHtml($user->getFirstname());?></a>
		<?php else: ?>
		<?php echo $this->escapeHtml($user->getFirstname());?>
		<?php endif;?>
    </td>
    <td><a href="mailto:<?php echo $this->escapeHtml($user->getEmail());?>" title="<?php echo $this->translate('Send an email'); ?>"><i class="icon-envelope icon-linkcolor"></i> <?php echo $this->escapeHtml($user->getEmail());?></a></td>
    <td>
		<?php if ($user->isActive()):?>
			<span class="label label-success" style="padding:5px;"><i class="icon-ok icon-white"></i> <?php echo $this->translate('Account enabled'); ?></span>
		<?php else:?>
			<span class="label label-important" style="padding:5px;"><i class="icon-ban-circle icon-white"></i> <?php echo $this->translate('Account disabled'); ?></span>
		<?php endif;?>
    </td>
    <td class="text-right action-bar action-bar-container">
		<?php if ($this->acl()->isAllowed("admin_edit_user")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('admin/user',
            array('action'=>'edit', 'id' => $user->getId()));?>"><i class="icon-edit icon-linkcolor"></i> <?php echo $this->translate('edit'); ?></a>
        </div> 
		<?php endif;?>
    	<?php if ($this->acl()->isAllowed("admin_delete_user")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('admin/user',
            array('action'=>'delete', 'id' => $user->getId()));?>"><i class="icon-trash icon-linkcolor"></i> <?php echo $this->translate('delete'); ?></a>
        </div> 
    	<?php endif;?>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else: ?>
<div class="well">
<?php echo $this->translate('No users.'); ?>
</div>
<?php endif; ?>