<?php
$title = $this->translate('Users');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/user', array('action'=>'add'));?>"><i class="icon-plus-sign icon-linkcolor"></i> <?php echo $this->translate('Add user'); ?></a>
</p>

<table class="table table-hover">
<thead>
<tr>
    <th><?php echo $this->translate('ID'); ?></th>
    <th><?php echo $this->translate('Name'); ?></th>
    <th><?php echo $this->translate('Firstname'); ?></th>
    <th><?php echo $this->translate('Email'); ?></th>
    <th><?php echo $this->translate('Active?'); ?></th>
    <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->getId());?></td>
	<td><?php echo $this->escapeHtml($user->getLastname());?></td>
    <td><?php echo $this->escapeHtml($user->getFirstname());?></td>
    <td><?php echo $this->escapeHtml($user->getEmail());?></td>
    <td><?php echo $user->isActive()?"Oui":"Non";?></td>
    <td class="text-right">
        <a href="<?php echo $this->url('admin/user',
            array('action'=>'edit', 'id' => $user->getId()));?>"><i class="icon-edit icon-linkcolor"></i> <?php echo $this->translate('edit'); ?></a> | 
        <a href="<?php echo $this->url('admin/user',
            array('action'=>'delete', 'id' => $user->getId()));?>"><i class="icon-trash icon-linkcolor"></i> <?php echo $this->translate('delete'); ?></a>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>