<?php
$user = $this->user;
$title = $this->translateReplace('User %name%', array('name' => $user->getDisplayName()));
$this->headTitle($title);
?>
<?php echo $this->partial('partial/user-info.phtml', array(
	'user' => $user,
	'show_actions' => true
)); ?>
<div class="p">
<?php $user_roles = $user->getRoles(); ?>
<span class="muted"><i class="icon-suitcase"></i> <?php echo $this->translate('Roles: '); ?></span>
<?php if (count($user_roles)): ?>
<ul style="display:inline-block;vertical-align:top;">
<?php foreach ($this->all_roles as $role): ?>
	<?php if (in_array($role->getId(), $user_roles)): ?>
		<li>
			<?php if ($this->acl()->isAllowed("admin_show_role")): ?>
			<a href="<?php echo $this->url('admin/role',
            array('action'=>'show', 'id' => $role->getId()));?>" title="<?php echo $role->getDescr();?>"><?php echo $role->getName();?></a>
            <?php else: ?>
            <?php echo $role->getName();?>
            <?php endif; ?>
        </li>
	<?php endif;?>
<?php endforeach; ?>
</ul>
<?php else: ?>
<?php echo $this->translate('None'); ?>
<?php endif; ?>
</div>

<?php if ($this->return_url): ?>
<p>
<a href="<?php echo $this->return_url; ?>" class="btn btn-primary"><?php echo $this->translate('Back'); ?></a>
<?php if ($user->getRegistrationToken() && $this->acl()->isAllowed("admin_add_user")): ?>
<a class="btn btn-secondary" href="<?php echo $this->url('admin/user',
            array('action'=>'creation-email', 'id' => $this->user->getId()));?>"><i class="icon-envelope-alt icon-linkcolor"></i> <?php echo $this->translate('Resend account validation email'); ?></a>
<?php endif; ?>
</p>
<?php endif; ?>
