<h1><?php echo $this->translate('Account recovery'); ?></h1>
<p>
<?php echo $this->translate("Your forgot your password and asked to recover your account.<br/>Please follow the link below to set a new password for your account: "); ?>
</p>
<center>
<?php $recoverUrl = $this->baseUrl($this->url('reset-password', ['token' => $this->token])); ?>
<a href="<?php echo $this->escapehtmlattr($recoverUrl); ?>"><?php echo $this->escapehtml($recoverUrl); ?></a>
</center>
