<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Costume\Module'                               => __DIR__ . '/Module.php',
  'Costume\Form\ColorFilter'                     => __DIR__ . '/src/Costume/Form/ColorFilter.php',
  'Costume\Controller\AdminColorController'      => __DIR__ . '/src/Costume/Controller/AdminColorController.php',
  'Costume\Controller\AdminController'           => __DIR__ . '/src/Costume/Controller/AdminController.php',
  'Costume\Controller\AbstractCostumeController' => __DIR__ . '/src/Costume/Controller/AbstractCostumeController.php',
  'Costume\Controller\ConsoleController'         => __DIR__ . '/src/Costume/Controller/ConsoleController.php',
  'Costume\Controller\CostumeController'         => __DIR__ . '/src/Costume/Controller/CostumeController.php',
  'Costume\Controller\AdminMaterialController'   => __DIR__ . '/src/Costume/Controller/AdminMaterialController.php',
  'Costume\Model\Import\OldExcel'                => __DIR__ . '/src/Costume/Model/Import/OldExcel.php',
  'Costume\Model\Costume'                        => __DIR__ . '/src/Costume/Model/Costume.php',
  'Costume\Model\ColorTable'                     => __DIR__ . '/src/Costume/Model/ColorTable.php',
  'Costume\Model\CostumeTable'                   => __DIR__ . '/src/Costume/Model/CostumeTable.php',
  'Costume\Model\CostumePictureTable'            => __DIR__ . '/src/Costume/Model/CostumePictureTable.php',
  'Costume\Model\Color'                          => __DIR__ . '/src/Costume/Model/Color.php',
);
