<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Costume\Module'                               => __DIR__ . '/Module.php',
  'Costume\Controller\AbstractCostumeController' => __DIR__ . '/src/Costume/Controller/AbstractCostumeController.php',
  'Costume\Controller\ConsoleController'         => __DIR__ . '/src/Costume/Controller/ConsoleController.php',
  'Costume\Controller\CostumeController'         => __DIR__ . '/src/Costume/Controller/CostumeController.php',
  'Costume\Model\Import\OldExcel'                => __DIR__ . '/src/Costume/Model/Import/OldExcel.php',
  'Costume\Model\Costume'                        => __DIR__ . '/src/Costume/Model/Costume.php',
  'Costume\Model\CostumeTable'                   => __DIR__ . '/src/Costume/Model/CostumeTable.php',
);
