<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Costume\Module'                        => __DIR__ . '/Module.php',
    'Costume\Controller\ConsoleController' => __DIR__ . '/src/Costume/Controller/ConsoleController.php',
);
