<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'costume/costume/add'   => __DIR__ . '/view/costume/costume/add.phtml',
    'costume/costume/index' => __DIR__ . '/view/costume/costume/index.phtml',
);
