<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Form\ForgotPasswordFilter'                       => __DIR__ . '/src/User/Form/ForgotPasswordFilter.php',
    'User\Form\Password'                                   => __DIR__ . '/src/User/Form/Password.php',
    'User\Form\Login'                                      => __DIR__ . '/src/User/Form/Login.php',
    'User\Form\ForgotPassword'                             => __DIR__ . '/src/User/Form/ForgotPassword.php',
    'User\Form\UserFilter'                                 => __DIR__ . '/src/User/Form/UserFilter.php',
    'User\Form\LoginFilter'                                => __DIR__ . '/src/User/Form/LoginFilter.php',
    'User\Form\User'                                       => __DIR__ . '/src/User/Form/User.php',
    'User\Form\PasswordFilter'                             => __DIR__ . '/src/User/Form/PasswordFilter.php',
    'User\View\Helper\UserIdentity'                        => __DIR__ . '/src/User/View/Helper/UserIdentity.php',
    'User\Controller\ProfileController'                    => __DIR__ . '/src/User/Controller/ProfileController.php',
    'User\Controller\ConsoleController'                    => __DIR__ . '/src/User/Controller/ConsoleController.php',
    'User\Controller\AbstractUserController'               => __DIR__ . '/src/User/Controller/AbstractUserController.php',
    'User\Controller\AuthController'                       => __DIR__ . '/src/User/Controller/AuthController.php',
    'User\Controller\AdminController'                      => __DIR__ . '/src/User/Controller/AdminController.php',
    'User\Controller\Plugin\UserAuthentication'            => __DIR__ . '/src/User/Controller/Plugin/UserAuthentication.php',
    'User\Authentification\Storage\Session'                => __DIR__ . '/src/User/Authentification/Storage/Session.php',
    'User\Authentification\Adapter\DbCallbackCheckAdapter' => __DIR__ . '/src/User/Authentification/Adapter/DbCallbackCheckAdapter.php',
    'User\Model\UserTable'                                 => __DIR__ . '/src/User/Model/UserTable.php',
    'User\Model\User'                                      => __DIR__ . '/src/User/Model/User.php',
    'User\Module'                                          => __DIR__ . '/Module.php',
);
