<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'partial/user-info'                => __DIR__ . '/view/partial/user-info.phtml',
    'user/profile/profile-layout'      => __DIR__ . '/view/user/profile/profile-layout.phtml',
    'user/profile/edit'                => __DIR__ . '/view/user/profile/edit.phtml',
    'user/profile/show'                => __DIR__ . '/view/user/profile/show.phtml',
    'user/profile/changepassword'      => __DIR__ . '/view/user/profile/changepassword.phtml',
    'user/auth/login'                  => __DIR__ . '/view/user/auth/login.phtml',
    'user/auth/resetpassword'          => __DIR__ . '/view/user/auth/resetpassword.phtml',
    'user/auth/forgotpassword'         => __DIR__ . '/view/user/auth/forgotpassword.phtml',
    'user/admin/delete'                => __DIR__ . '/view/user/admin/delete.phtml',
    'user/admin/add'                   => __DIR__ . '/view/user/admin/add.phtml',
    'user/admin/index'                 => __DIR__ . '/view/user/admin/index.phtml',
    'user/admin/edit'                  => __DIR__ . '/view/user/admin/edit.phtml',
    'user/admin/show'                  => __DIR__ . '/view/user/admin/show.phtml',
    'email/password_recovery'          => __DIR__ . '/view/email/password_recovery.phtml',
    'email/password_recovery_disabled' => __DIR__ . '/view/email/password_recovery_disabled.phtml',
    'email/account_creation'           => __DIR__ . '/view/email/account_creation.phtml',
);
