<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/index/index'   => __DIR__ . '/view/application/index/index.phtml',
    'partial/paginator-sliding' => __DIR__ . '/view/partial/paginator-sliding.phtml',
    'partial/results-status'    => __DIR__ . '/view/partial/results-status.phtml',
    'partial/breadcrumb'        => __DIR__ . '/view/partial/breadcrumb.phtml',
    'partial/table-sorter'      => __DIR__ . '/view/partial/table-sorter.phtml',
    'partial/result-status'     => __DIR__ . '/view/partial/result-status.phtml',
    'error/index'               => __DIR__ . '/view/error/index.phtml',
    'error/404'                 => __DIR__ . '/view/error/404.phtml',
    'error/403'                 => __DIR__ . '/view/error/403.phtml',
    'layout/layout'             => __DIR__ . '/view/layout/layout.phtml',
);
