<?php
$title = 'Delete role';
$this->headTitle($title);
$user = $this->user;
?>
<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>

<p>
<?php echo $this->translateReplace("Are you sure that you want to delete role '%name%'?", array('name' => $this->escapeHtml($this->role->getName()))); ?>
</p>

<?php
$url = $this->url('admin/role', array(
    'action' => 'delete',
    'id'     => $this->role->getId(),
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $this->role->getId(); ?>" />
    <button type="submit" class="btn" name="del" value="no"><?php echo $this->translate('No'); ?></button>
    <button type="submit" class="btn btn-primary" name="del" value="yes"><?php echo $this->translate('Yes'); ?></button>
</div>
</form>