<?php
$title = $this->translate('Roles');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin/role', array('action'=>'add'));?>"><i class="icon-plus-sign icon-linkcolor"></i> <?php echo $this->translate('Add role'); ?></a>
</p>

<?php if (count($this->roles)): ?>
<table class="table table-hover">
<thead>
<tr>
    <th><?php echo $this->translate('ID'); ?></th>
    <th><?php echo $this->translate('Name'); ?></th>
    <th><?php echo $this->translate('Description'); ?></th>
    <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->roles as $role) : ?>
<tr>
    <td><?php echo $this->escapeHtml($role->getId());?></td>
	<td><a href="<?php echo $this->url('admin/role',
            array('action'=>'show', 'id' => $role->getId()));?>"><?php echo $this->escapeHtml($role->getName());?></a></td>
    <td><?php echo $this->escapeHtml($role->getDescr());?></td>
    <td class="text-right">
        <a href="<?php echo $this->url('admin/role',
            array('action'=>'edit', 'id' => $role->getId()));?>"><i class="icon-edit icon-linkcolor"></i> <?php echo $this->translate('edit'); ?></a> | 
        <a href="<?php echo $this->url('admin/role',
            array('action'=>'delete', 'id' => $role->getId()));?>"><i class="icon-trash icon-linkcolor"></i> <?php echo $this->translate('delete'); ?></a>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else: ?>
<div class="well">
<?php echo $this->translate('No roles.'); ?>
</div>
<?php endif; ?>