<?php
$title = $this->translate('Roles');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="p action-bar action-bar-container">
	<?php if ($this->acl()->isAllowed("admin_add_role")): ?>
	<div class="action-bar-item">
	<a href="<?php echo $this->url('admin/role', array('action'=>'add'));?>"><i class="fa fa-plus-circle"></i> <?php echo $this->translate('Add role'); ?></a>
	</div>
	<?php endif; ?>
</div>

<?php if (count($this->roles)): ?>
<table class="table table-hover">
<thead>
<tr>
    <th><?php echo $this->translate('ID'); ?></th>
    <th><?php echo $this->translate('Name'); ?></th>
    <th><?php echo $this->translate('Description'); ?></th>
    <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->roles as $role) : ?>
<tr>
    <td><?php echo $this->escapeHtml($role->getId());?></td>
	<td>
		<?php if ($this->acl()->isAllowed("admin_show_role")): ?>
		<a href="<?php echo $this->url('admin/role',
            array('action'=>'show', 'id' => $role->getId()));?>"><?php echo $this->escapeHtml($role->getName());?></a>
        <?php else: ?>
        <?php echo $this->escapeHtml($role->getName());?>
		<?php endif; ?>
    </td>
    <td><?php echo $this->escapeHtml($role->getDescr());?></td>
    <td class="text-right action-bar action-bar-container">
		<?php if ($this->acl()->isAllowed("admin_edit_role")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('admin/role',
            array('action'=>'edit', 'id' => $role->getId()));?>"><i class="fa fa-pencil"></i> <?php echo $this->translate('edit'); ?></a>
        </div> 
		<?php endif;?>
    	<?php if ($this->acl()->isAllowed("admin_delete_role")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('admin/role',
            array('action'=>'delete', 'id' => $role->getId()));?>"><i class="fa fa-trash-o"></i> <?php echo $this->translate('delete'); ?></a>
        </div> 
    	<?php endif;?>
    </td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php else: ?>
<div class="well">
<?php echo $this->translate('No roles.'); ?>
</div>
<?php endif; ?>