<?php
$title = $this->translateReplace("'%name%' role's details", array('name' => $this->role->getName()));
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>
<div class="p action-bar action-bar-container">
		<?php if ($this->acl()->isAllowed("admin_edit_role")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('admin/role',
            array('action'=>'edit', 'id' => $this->role->getId()));?>"><i class="icon-edit icon-linkcolor"></i> <?php echo $this->translate('edit'); ?></a>
        </div> 
		<?php endif;?>
    	<?php if ($this->acl()->isAllowed("admin_delete_role")): ?>
		<div class="action-bar-item">
    	<a href="<?php echo $this->url('admin/role',
            array('action'=>'delete', 'id' => $this->role->getId()));?>"><i class="icon-trash icon-linkcolor"></i> <?php echo $this->translate('delete'); ?></a>
        </div> 
    	<?php endif;?>
</div>
<p>
<?php echo $this->escapeHtml($this->role->getDescr()); ?>
</p>
<p>
<?php echo $this->partial('partial/rights-list.phtml', array(
	'rights' => $this->all_rights,
	'show_checked_mode' => true, 
	'checked_rights' => $this->role->getRights()
)); ?>
</p>
<a href="<?php echo $this->return_url; ?>" class="btn btn-primary"><?php echo $this->translate('Back'); ?></a>