<?php
$title = $this->translate("Costumes' colors");
$this->headTitle($title);
$this->headLink()->offsetSetStylesheet(100, $this->basePath() . '/css/bootstrap-colorpicker.min.css');
$this->headscript()->offsetSetFile(100, $this->basePath() . '/js/bootstrap-colorpicker.min.js');
if ($this->acl()->isAllowed("admin_costumes_colors")) {
	$this->headscript()->offsetSetFile(101, $this->basePath() . '/js/costume/colors_admin.js');
}
?>

<div class="row-fluid">
	<div class="span6">
		<div class="p action-bar action-bar-container">
			<?php if ($this->acl()->isAllowed("admin_costumes_colors")): ?>
			<div class="action-bar-item">
			<a href="#" id="add-color-link"><i class="icon-plus-sign icon-linkcolor"></i> <?php echo $this->translate('Add a color'); ?></a>
			</div>
			<?php endif; ?>
		</div>
		<table class="table table-hover table-bordered" id="colors-list">
		<tbody>
		<?php if (count($this->colors)): ?>
		<?php foreach ($this->colors as $color) : ?>
		<tr class="color-row" data-id="<?php echo $this->escapeHtmlAttr($color->getId()); ?>" data-name="<?php echo $this->escapeHtmlAttr($color->getName()); ?>" data-color="<?php echo $this->escapeHtmlAttr($color->getColorCode()); ?>">
			<td style="width:20px;" class="text-center sort-handle"></td>
			<td class="name">
				<?php echo $this->escapeHtml($color->getName()); ?>
			</td>
			<td style="width:20px;background-color:#<?php echo $this->escapeHtmlAttr($color->getColorCode()); ?>;" class="color" title="#<?php echo $this->escapeHtmlAttr($color->getColorCode()); ?>"></td>
			<td class="delete-color text-center" style="width:20px;"><a href="#"><i class="icon-trash icon-linkcolor"></i></a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif;?>
		</tbody>
		</table>
	<div class="well" <?php if (count($this->colors)) echo ' style="display:none"'; ?>>
	<?php echo $this->translate('No colors.'); ?>
	</div>
	</div>
	<div class="span6">
		<div id="color-form-container" data-spy="affix" data-offset-top="55">
			<form id="edit-color" style="padding:10px;display:none;">
				<fieldset>
				  	<legend><?php echo $this->translate('Edit color'); ?></legend>
					<input type="hidden" name="id" value=""/>
				  	<label><?php echo $this->translate('Name: '); ?></label>
				    <input type="text" name="name"><br/>
				    <label><?php echo $this->translate('Color: '); ?></label>
					<div class="input-append colorpicker-component color-picker" id="edit-color-picker" data-color="" data-color-format="hex">
					    <input type="text" name="color" value=""/>
					    <span class="add-on"><i style=""></i></span>
					</div>
				    <br/>
				    
				    <a class="btn cancel-link"><?php echo $this->translate('Cancel'); ?></a>
				    <input type="submit" class="btn btn-primary save-link" value="<?php echo $this->translate('Edit'); ?>">
				</fieldset>
				<div class="alert alert-danger edit-error" style="display:none;margin-top:10px;">
				</div>
			</form>
			<form id="add-color" style="padding:10px;display:none;">
				<fieldset>
				  	<legend><?php echo $this->translate('Add a color'); ?></legend>
				  	<label><?php echo $this->translate('Name: '); ?></label>
				    <input type="text" name="name"><br/>
				    <label><?php echo $this->translate('Color: '); ?></label>
					<div class="input-append colorpicker-component color-picker" id="add-color-picker" data-color="" data-color-format="hex">
					    <input type="text" name="color" value=""/>
					    <span class="add-on"><i style=""></i></span>
					</div>
				    <br/>
				    
				    <a class="btn cancel-link"><?php echo $this->translate('Cancel'); ?></a>
				    <input type="submit" class="btn btn-primary save-link" value="<?php echo $this->translate('Add'); ?>">
				</fieldset>
				<div class="alert alert-danger add-error" style="display:none;margin-top:10px;">
				</div>
			</form>
		</div>
	</div>
</div>

<div class="modal hide" id="delete-color-dialog">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h3><?php echo $this->translate('Delete a color'); ?></h3>
  </div>
  <div class="modal-body">
    <p><?php echo $this->translate('Do you really want to delete this color?'); ?></p>
    <input type="hidden" name="color_delete_id"/>
    <div class="text-center">
    	<h4 class="delete-color-name" style="display:inline-block;vertical-align:middle;"></h4>
    	<div class="delete-color-preview" style="display:inline-block;height:36px;width:36px;border:solid 1px #DDD;border-radius:4px;margin-left:10px;vertical-align:middle;"></div>
    </div>
    <p class="alert alert-info" style="margin-bottom:0px;margin-top:20px;"><i class="icon-info-sign"></i> <?php echo $this->translate('The color will be removed from all costumes using it.'); ?></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal" ><?php echo $this->translate('No'); ?></a>
    <a href="#" class="btn btn-primary button-yes"><?php echo $this->translate('Yes'); ?></a>
  </div>
</div>

<script type="text/javascript">
	var gTransLoading = '<?php echo $this->escapeJs($this->translate('Saving...')); ?>';
	var gColorRowTemplate = '<tr class="color-row" data-id="" data-name="" data-color="">' +
							'<td style="width:20px;" class="text-center sort-handle"></td>'+
							'<td class="name">'+
							'</td>'+
							'<td style="width:20px;" class="color"></td>'+
							'<td class="delete-color text-center" style="width:20px;"><a href="#"><i class="icon-trash icon-linkcolor"></i></a></td>' +
							'</tr>';
</script>
