<?php
$title = $this->translate("Costumes' parts & types");
$this->headTitle($title);
if ($this->acl()->isAllowed("admin_costumes_parts")) {
	$this->headscript()->offsetSetFile(101, $this->basePath() . '/js/costume/parts_admin.js');
}
?>
<h5><?php echo $this->translate('Double-clic a part name to edit.'); ?></h5>
<?php if (count($this->parts)): ?>
	<form id="part-edit-form-template" class="part-edit-form" style="display:none;margin-bottom:0px;">
		<div class="input-append" style="margin-bottom:0px;">
			<input type="hidden" name="id"/>
			<input name="name" type="text"/>
			<button class="btn btn-primary" type="submit"><i class="fa fa-check"></i></button>
			<button class="btn btn-default" type="button" name="cancel"><i class="fa fa-times"></i></button>
		</div>
		<span class="text-error edit-error"></span>
	</form>
	
	<table class="table table-hover table-bordered" id="parts-list">
	<tbody>
	<?php foreach ($this->parts as $part) : ?>
	<tr class="part-row" data-id="<?php echo $this->escapeHtmlAttr($part->getId()); ?>" data-name="<?php echo $this->escapeHtmlAttr($part->getName()); ?>">
		<td class="name">
			<?php echo $this->escapeHtml($part->getName()); ?>
		</td>
		<td class="delete-part text-center vertical-center" style="width:20px;"><a href="#"><i class="fa fa-trash-o"></i></a></td>
	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
<?php else: ?>
	<div class="well">
	<?php echo $this->translate('No parts.'); ?>
	</div>
<?php endif;?>

<div class="modal hide" id="delete-part-dialog">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h3><?php echo $this->translate('Delete a part'); ?></h3>
  </div>
  <div class="modal-body">
    <p><?php echo $this->translate('Do you really want to delete this part?'); ?></p>
    <input type="hidden" name="part_delete_id"/>
    <div class="text-center">
    	<h4 class="delete-part-name" style="display:inline-block;vertical-align:middle;"></h4>
    </div>
    <p class="alert alert-info" style="margin-bottom:0px;margin-top:20px;"><i class="fa fa-info-circle"></i> <?php echo $this->translate('The part will be removed from all costumes using it, as type or part.'); ?></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal" ><?php echo $this->translate('No'); ?></a>
    <a href="#" class="btn btn-primary button-yes"><?php echo $this->translate('Yes'); ?></a>
  </div>
</div>

<script type="text/javascript">
	var gTransLoading = '<?php echo $this->escapeJs($this->translate('Saving...')); ?>';
</script>
