<?php
$title = $this->translate("Costumes' tags");
$this->headTitle($title);
if ($this->acl()->isAllowed("admin_costumes_tags")) {
	$this->headscript()->offsetSetFile(101, $this->basePath() . '/js/costume/tags_admin.js');
}
?>

<?php if (count($this->tags)): ?>
	<form id="tag-edit-form-template" class="tag-edit-form" style="display:none;margin-bottom:0px;">
		<div class="input-append" style="margin-bottom:0px;">
			<input type="hidden" name="id"/>
			<input name="name" type="text"/>
			<button class="btn btn-primary" type="submit"><i class="icon-ok icon-white"></i></button>
			<button class="btn btn-default" type="button" name="cancel"><i class="icon-remove"></i></button>
		</div>
		<span class="text-error edit-error"></span>
	</form>
	
	<table class="table table-hover table-bordered" id="tags-list">
	<tbody>
	<?php foreach ($this->tags as $tag) : ?>
	<tr class="tag-row" data-id="<?php echo $this->escapeHtmlAttr($tag->getId()); ?>" data-name="<?php echo $this->escapeHtmlAttr($tag->getName()); ?>">
		<td class="name">
			<?php echo $this->escapeHtml($tag->getName()); ?>
		</td>
		<td class="delete-tag text-center vertical-center" style="width:20px;"><a href="#"><i class="icon-trash icon-linkcolor"></i></a></td>
	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
<?php else: ?>
	<div class="well">
	<?php echo $this->translate('No tags.'); ?>
	</div>
<?php endif;?>

<div class="modal hide" id="delete-tag-dialog">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h3><?php echo $this->translate('Delete a tag'); ?></h3>
  </div>
  <div class="modal-body">
    <p><?php echo $this->translate('Do you really want to delete this tag?'); ?></p>
    <input type="hidden" name="tag_delete_id"/>
    <div class="text-center">
    	<h4 class="delete-tag-name" style="display:inline-block;vertical-align:middle;"></h4>
    </div>
    <p class="alert alert-info" style="margin-bottom:0px;margin-top:20px;"><i class="icon-info-sign"></i> <?php echo $this->translate('The tag will be removed from all costumes using it.'); ?></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal" ><?php echo $this->translate('No'); ?></a>
    <a href="#" class="btn btn-primary button-yes"><?php echo $this->translate('Yes'); ?></a>
  </div>
</div>

<script type="text/javascript">
	var gTransLoading = '<?php echo $this->escapeJs($this->translate('Saving...')); ?>';
</script>
