<?php echo $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Miranda'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

        <!-- CSS -->
        <?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>
        <?php if (count($this->css)) foreach ($this->css as $css) $this->headLink()->appendStylesheet($this->basePath() . '/' . $css); ?>
        <?php echo $this->headLink(); ?>
        
	    <!-- JS Scripts -->
        <?php if (count($this->js)) foreach ($this->js as $js) $this->headScript()->appendFile($this->basePath() . '/' . $js); ?>
	    <?php $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9')); ?>
	    <?php echo $this->headScript(); ?>

    </head>
    <body>
    	<div id="wrap">
            <?php if($this->userIdentity()): ?>
            <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="<?php echo $this->url('home') ?>">Miranda</a>
                    <div class="nav-collapse collapse">
                    <?php echo $this->navigation('navigation')
                    		->menu()
                            ->setMinDepth(0)
                            ->setMaxDepth(0)
                            ->setUlClass('nav')
                            ->render(); 
                    ?>
                    <ul class="nav pull-right">
                        <li><a href="<?php echo $this->url('profile') ?>"><i class="icon-user icon-white"></i>&nbsp;<?php echo $this->userIdentity()->getDisplayName(); ?></a></li>
                        <li><a href="<?php echo $this->url('logout') ?>"><i class="icon-off icon-white"></i>&nbsp;Déconnexion</a></li>
                    </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div> <!-- /navbar-inner -->
            <?php
            $submenu = $this->navigation('navigation')
	       		->menu()
	            ->setOnlyActiveBranch(true)
	            ->setRenderParents(false)
	            ->setMinDepth(1)
	            ->setMaxDepth(1)
	            ->setUlClass('nav')
	            ->render();
            if (!empty($submenu)): ?>
            <div class="subnav">
                <div class="container">
                    <div class="nav-collapse collapse">
                    <?php echo $submenu; ?>
                    </div> <!--/.nav-collapse -->
                </div>
            </div>
            <?php endif; ?>
            </div>
            <?php else: // userIdentity; ?>
            <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login'); ?></a>
                </div>
            </div>
            </div>        
	        <?php endif; // userIdentity; ?>
        
	        <div class="container">
	            <?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setRenderInvisible(true)->setPartial(array('breadcrumb', 'Application')); ?>
				<?php echo $this->partial('results-status'); ?>
	            <?php echo $this->content; ?>
	        </div> <!-- /container -->
	        
	        <div id="push"></div>
	    </div> <!-- /#wrap -->
	    
	    <footer id="footer">
	        <div class="container">
	            <p>&copy; 2013 - <?php echo date('Y') ?> <a href="http://www.compagniemiranda.com/" target="_blank"><?php echo $this->translate('Compagnie Miranda'); ?></a>. <?php echo $this->translate('All rights reserved.') ?></p>
	        </div>
	    </footer>
	    
	    <?php echo $this->inlineScript(); ?>
    
    </body>
</html>
