<?php if ($this->show_names): ?>
<a class="right-btn-show-name btn" href="#"><i class="fa fa-code"></i></a><br/><br/>
<?php endif; ?>

<ul class="rights-group">
<?php foreach($this->rights as $group): ?>
	<li>
		<span class="group-name">
		<?php if ($this->edit_mode): ?>
			<input type="checkbox" id="rights-group-<?php echo $group->group_id; ?>" class="rights-group-checker" data-group-id="<?php echo $group->group_id; ?>"/>
			<label for="rights-group-<?php echo $group->group_id; ?>"><?php echo $this->translate($group->descr); ?></label>
		<?php else:?>
			<?php echo $this->translate($group->descr); ?>
		<?php endif; ?>
		</span>
		<ul class="rights-list">
		<?php foreach($group->rights as $right): ?>
		<li>
		<?php if ($this->edit_mode): ?>
			<input type="checkbox" name="rights[]" value="<?php echo $right->id; ?>" <?php if (in_array($right->id, $this->checked_rights)) echo 'checked="checked"'; ?> id="rights-group-right-<?php echo $right->id; ?>" class="rights-group-right-checker" data-group-id="<?php echo $group->group_id; ?>"/>
			<label for="rights-group-right-<?php echo $right->id; ?>"><?php echo $this->translate($right->descr); ?></label>
		<?php elseif ($this->show_checked_mode):?>
			<?php if (in_array($right->id, $this->checked_rights)): ?>
				<i class="fa fa-check fa-fw"></i> <?php echo $this->translate($right->descr); ?>
			<?php else: ?>
				<span class="muted"><i class="fa fa-fw"></i> <?php echo $this->translate($right->descr); ?></span>
			<?php endif; ?>
		<?php else:?>
			<?php echo $this->translate($right->descr); ?>
			<?php if ($this->show_names): ?>
            <div class="rights-show-name"><?php echo $this->translate($right->name); ?></div>
            <?php endif; ?>
		<?php endif; ?>
		</li>
		<?php endforeach; ?>
		</ul>
	</li>
<?php endforeach;?>
</ul>

<?php if ($this->show_names): ?>
    <script type="text/javascript">
        $(document).ready(function() {
            $('.rights-show-name').hide().dblclick(function(e) {
                e.preventDefault();
                var $this = $(this);
                if (document.selection) {
                    var range = document.body.createTextRange();
                    range.moveToElementText($this.get(0));
                    range.select();
                } else if (window.getSelection) {
                    var range = document.createRange();
                    range.selectNodeContents($this.get(0));
                    window.getSelection().addRange(range);
                }
            });

            $('.right-btn-show-name').click(function(e) {
                e.preventDefault();
                var $this = $(this);
                if ($this.hasClass('active')) {
                    $('.rights-show-name').hide();
                    $this.removeClass('active');
                } else {
                    $('.rights-show-name').show();
                    $this.addClass('active');
                }
            });
        });
    </script>
<?php endif; ?>

<?php if ($this->edit_mode): ?>
<script type="text/javascript">
$(document).ready(function() {
	$('input[type=checkbox].rights-group-checker').click(function() {
		var group_id = $(this).attr('data-group-id');
		var checked = $(this).is(':checked');
		$('input[type=checkbox][data-group-id='+group_id+'].rights-group-right-checker').prop('checked', checked);
	});
	$('input[type=checkbox].rights-group-right-checker').click(function() {
		var group_id = $(this).attr('data-group-id');
		var checked = true;

		if ($(this).is(':checked')) {
			// Is all other checkbox of the right group checked?
			$('input[type=checkbox][data-group-id='+group_id+'].rights-group-right-checker').each(function() {
				if (!$(this).is(':checked')) {
					checked = false;
				}
			});
		} else {
			checked = false;
		}
		
		$('input[type=checkbox][data-group-id='+group_id+'].rights-group-checker').prop('checked', checked);
	});
	$('input[type=checkbox].rights-group-right-checker').each(function() {
		$(this).triggerHandler('click');
	});
});
</script>
<?php endif; ?>
