<?php
$title = $this->translate('Rights');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br/>
<?php echo $this->partial('partial/rights-list.phtml', ['rights' => $this->rights, 'show_names' => $this->acl()->isAllowed("developer")]); ?>

<?php if ($this->acl()->isAllowed("admin_update_acl")): ?>
	<a href="<?php echo $this->url('admin/right', array('action' => 'update'));?>" class="btn"><?php echo $this->translate('Update ACL in cache'); ?></a>
<?php endif; ?>
