<?php
$title = $this->translate('Admin');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if ($this->acl()->isAllowed("admin_list_users")): ?>
<p style="margin-top:30px;">
<a class="admin-btn btn" href="<?php echo $this->url('admin/user'); ?>">
<i class="icon-user icon-3x"></i><br/>
<span class="title"><?php echo $this->translate('Users'); ?></span>
</a>
<?php endif; ?>

<?php if ($this->acl()->isAllowed("admin_list_roles")): ?>
<a class="admin-btn btn" href="<?php echo $this->url('admin/role'); ?>">
<i class="icon-suitcase icon-3x"></i><br/>
<span class="title"><?php echo $this->translate('Roles'); ?></span>
</a>
<?php endif; ?>

<?php if ($this->acl()->isAllowed("admin_list_rights")): ?>
<a class="admin-btn btn" href="<?php echo $this->url('admin/right'); ?>">
<i class="icon-key icon-3x"></i><br/>
<span class="title"><?php echo $this->translate('Rights'); ?></span>
</a>
</p>
<?php endif; ?>
