<?php
$title = $this->translate('Admin');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p style="margin-top:30px;">
<a class="admin-btn btn" href="<?php echo $this->url('admin/user'); ?>">
<img src="img/admin/icon-users.png" alt="<?php echo $this->translate('Users'); ?>"/><br/>
<span class="title"><?php echo $this->translate('Users'); ?></span>
</a>

<a class="admin-btn btn" href="<?php echo $this->url('admin/role'); ?>">
<img src="img/admin/icon-roles.png" alt="<?php echo $this->translate('Roles'); ?>"/><br/>
<span class="title"><?php echo $this->translate('Roles'); ?></span>
</a>

<a class="admin-btn btn" href="<?php echo $this->url('admin/right'); ?>">
<img src="img/admin/icon-rights.png" alt="<?php echo $this->translate('Rights'); ?>"/><br/>
<span class="title"><?php echo $this->translate('Rights'); ?></span>
</a>
</p>